# Generated by Django 5.1 on 2024-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Officer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_ca", models.CharField(default="unknown", max_length=255)),
                ("id_citizen", models.CharField(default="unknown", max_length=255)),
                ("name", models.CharField(default="unknown", max_length=255)),
                ("gender", models.CharField(default="unknown", max_length=255)),
                ("date_of_birth", models.DateField(null=True)),
                ("date_of_enlistment", models.DateField(null=True)),
                ("date_join_party", models.DateField(null=True)),
                ("home_town", models.CharField(default="unknown", max_length=255)),
                (
                    "current_residence",
                    models.CharField(default="unknown", max_length=255),
                ),
                ("blood_type", models.CharField(default="unknown", max_length=255)),
                ("education", models.CharField(default="unknown", max_length=255)),
                ("certi_of_IT", models.CharField(default="unknown", max_length=255)),
                (
                    "certi_of_foreign_language",
                    models.CharField(default="unknown", max_length=255),
                ),
                (
                    "political_theory",
                    models.CharField(default="unknown", max_length=255),
                ),
                ("military_rank", models.CharField(default="unknown", max_length=255)),
                ("rank_type", models.CharField(default="unknown", max_length=255)),
                ("position", models.CharField(default="unknown", max_length=255)),
                ("work_unit", models.CharField(default="unknown", max_length=255)),
                ("military_type", models.CharField(default="unknown", max_length=255)),
                ("equipment_type", models.CharField(default="unknown", max_length=255)),
                ("size_of_shoes", models.CharField(default="unknown", max_length=255)),
                ("size_of_hat", models.CharField(default="unknown", max_length=255)),
                (
                    "size_of_clothes",
                    models.CharField(default="unknown", max_length=255),
                ),
                (
                    "bank_account_BIDV",
                    models.CharField(default="unknown", max_length=255),
                ),
                ("phone_number", models.CharField(default="unknown", max_length=255)),
                ("laudatory", models.CharField(default="unknown", max_length=255)),
                ("punishment", models.CharField(default="unknown", max_length=255)),
            ],
        ),
    ]
