# Generated by Django 5.1 on 2024-08-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="Officer",
        ),
    ]
