# Generated by Django 5.1 on 2024-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0002_rename_person_officer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officer",
            name="address",
        ),
        migrations.AddField(
            model_name="officer",
            name="bank_account_BIDV",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="blood_type",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="certi_of_IT",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="certi_of_foreign_language",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="current_residence",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="date_join_party",
            field=models.DateField(default="unknown"),
        ),
        migrations.AddField(
            model_name="officer",
            name="date_of_enlistment",
            field=models.DateField(default="unknown"),
        ),
        migrations.AddField(
            model_name="officer",
            name="education",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="equipment_type",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="gender",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="home_town",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="id_citizen",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="laudatory",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="military_rank",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="military_type",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="phone_number",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="political_theory",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="position",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="punishment",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="rank_type",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="size_of_clothes",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="size_of_hat",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="size_of_shoes",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="officer",
            name="work_unit",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="officer",
            name="date_of_birth",
            field=models.DateField(default="unknown"),
        ),
        migrations.AlterField(
            model_name="officer",
            name="id_ca",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="officer",
            name="name",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
