GENERAL_INFO_FIELDS = {
    "id_ca": "Số hiệu - Số hồ sơ",
    "birth_name": "Họ và tên khai sinh",
    "current_name": "Tên đang dùng",
    "gender": "Giới tính",
    "birth_place": "Nơi sinh",
    "current_residence": "Chỗ ở hiện nay",
    "folk": "Dân tộc",
    "religion": "Tôn giáo",
    "date_of_birth": "Ngày sinh",
    "month_join_group": "Tháng năm vào Đoàn",
    "group": "Đoàn thể",
    "month_join_party": "Tháng năm vào Đảng",
    "month_join_party_official": "Tháng năm chính thức",
    "party_card_number": "Số thẻ Đảng",
    "party_position": "Chức vụ Đảng",
    "month_recruit": "Tháng năm tuyển dụng",
    "month_join_CA": "Tháng năm vào CA",
    "recruit_unit": "Đơn vị tuyển",
    "recruit_source": "Nguồn tuyển",
    "unit_notation": "Ký hiệu đơn vị",
    "position": "Chức vụ",
    "military_rank": "Cấp bậc",
    "salary_coefficient": "Hệ số lương",
    "salary_decision": "Quyết định lương",
    "salary_decision_year": "Năm quyết định lương",
    "work_unit": "Đơn vị công tác",
    "military_type": "Lực lượng",
    "rank_type": "Loại hàm",
    "equipment_type": "Quân trang",
    "size_of_shoes": "Giày",
    "size_of_hat": "Mũ",
    "size_of_clothes": "Quần áo",
    "specialized_work": "Công tác chuyên trách",
    "maneuver_decision": "Quyết định điều động",
    "other_work": "Công tác khác",
    "most_work": "Công tác làm nhiều nhất",
    "education": "Trình độ học vấn",
    "certi_of_IT": "Tin học",
    "certi_of_foreign_language": "Ngoại ngữ",
    "political_theory": "Trình độ chính trị",
    "strength": "Năng lực sở trường",
    "blood_type": "Nhóm máu",
    "compete_title": "Danh hiệu",
    "policy_family": "Gia đình chính sách",
    "profile_address": "Địa chỉ hồ sơ",
    "phone_number": "Số điện thoại",
    "bank_account_BIDV": "Số TK BIDV",
    "insurance_number": "Số sổ bảo hiểm",
    "id_citizen": "Số CCCD",
    "date_update": "Ngày cập nhật",
}

GENERAL_INFO_DATE_FIELDS = [
    "month_join_group",
    "month_join_party",
    "month_join_party_official",
    "month_recruit",
    "month_join_CA",
]

